import { BondType, Constants } from './constants';

export const UI_DEFAULTS = {
  DEFAULT_INVESTMENT_AMOUNT: 1000,
  MIN_INVESTMENT_AMOUNT: 100,
  MAX_INVESTMENT_AMOUNT: 100000,
  INVESTMENT_STEP: 100,
  STRATEGY_FREQUENCY_MONTHS: 1,
  STRATEGY_DURATION_MONTHS: 12,
  STRATEGY_INITIAL_AMOUNT: 10000,
  STRATEGY_RECURRING_AMOUNT: 500,
  STRATEGY_REINVEST: true,
  STRATEGY_INFLATION_RATE: Constants.INFLATION_RATE,
  PORTFOLIO_DEFAULT_HORIZON_MONTHS: 12,
  PORTFOLIO_ANALYSIS_INFLATION_RATE: 5.0,
} as const;

export function createDefaultPortfolioItem() {
  return {
    bondType: BondType.OTS,
    amount: UI_DEFAULTS.DEFAULT_INVESTMENT_AMOUNT,
  };
}
